# Generated by Django 5.1.5 on 2025-02-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettertemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
